### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by airtel121** [openxc/android-webcam#20]
Process: com.ford.openxc.webcam, PID: 20416
                                                                        java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.ford.openxc.webcam-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libwebcam.so"
                                                                            at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                            at java.lang.System.loadLibrary(System.java:989)
                                                                            at com.ford.openxc.webcam.NativeWebcam.<clinit>(NativeWebcam.java:26)
                                                                            at com.ford.openxc.webcam.WebcamManager.onCreate(WebcamManager.java:28)
                                                                            at android.app.ActivityThread.handleCreateService(ActivityThread.java:2763)
                                                                            at android.app.ActivityThread.access$1800(ActivityThread.java:148)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1375)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5312)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by yakobom** [comment]
I had the same issue at the beginning - the so cannot be found, it was probably not built. You need to build the jni code (the shared object) via the command line. Then clean the project and rebuild it.
